import React from 'react'
import { CopyBlock, nord } from 'react-code-blocks';

import botsearch from '../assets/botsearch.svg'

function Sqlbar() {

  const code = `
  SELECT column_name(s)
  FROM table_name
  ORDER BY column_name(s)
  FETCH FIRST number ROWS ONLY;

  SELECT column_name(s)
  FROM table_name
  ORDER BY column_name(s)
  FETCH FIRST number ROWS ONLY;

  SELECT column_name(s)
  FROM table_name
  ORDER BY column_name(s)
  FETCH FIRST number ROWS ONLY;
  `

  return (
    <div className='overflow-scroll'>
        <span className="w-full grid grid-cols-3 gap-2 m-4">
          <span className='col-span-2 flex flex-col justify-center'>
            <h2 className='text-xl font-bold text-black'>SQL Query</h2>
            <p className=' text-gray-500 text-sm'>SQL query generated by the bot based on the prompt.</p>
          </span>
          <img className=' h-20 m-auto col-span-1' src={botsearch} alt=""/>
        </span>
        
        <CopyBlock
          customStyle={{marginTop: '1rem', marginBottom: '1rem'}}
          text={code}
          language="sql"
          showLineNumbers={false}
          theme={nord}
          wrapLongLines={true}
        />

    </div>
  )
}

export default Sqlbar
